=== icecube00/urib-tester/erib_Protocol.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by TEST (HOME) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:annotation>
			<xs:documentation>Корневой элемент</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="settings">
					<xs:annotation>
						<xs:documentation>Настройки подключения к ЕРИБ</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="operation" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Набор запросов atmAPI</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="specification" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Версия спецификации ЕРИБ</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="settings">
		<xs:annotation>
			<xs:documentation>Настройки подключения к ЕРИБ</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="request">
		<xs:annotation>
			<xs:documentation>Блок описания запроса</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="action">
					<xs:annotation>
						<xs:documentation>Блок запроса</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Название запроса (из спеки)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="id" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Номер запроса (уникальный [по возможности из спеки])</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="service" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Ключ сервиса оказываемой услуги [используется для раграничения прав доступа] (см. таблицу 3.3 в спеке)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="requireUDBO" use="optional">
				<xs:annotation>
					<xs:documentation>Признак необходимости запроса УДБО (см. таблицу 3.3 в спеке)</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="true"/>
						<xs:enumeration value="false"/>
						<xs:enumeration value="optional"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="params">
		<xs:annotation>
			<xs:documentation>Блок набора парамтеров запроса</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="param">
		<xs:annotation>
			<xs:documentation>Параметр запроса</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0">
				<xs:element ref="choice" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Группа зависимых параметров [Для парметров типа choice]</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="list">
					<xs:annotation>
						<xs:documentation>Фиксированный список допустимых значений [Для параметров типа - list или show]</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:choice>
			<xs:attribute name="text" type="xs:string">
				<xs:annotation>
					<xs:documentation>Текстовое описание парметра</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>Название параметра</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="value" type="xs:string">
				<xs:annotation>
					<xs:documentation>Значение по-умолчанию</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="required" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>Признак обязательности параметра</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:annotation>
					<xs:documentation>Тип параметра</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="bool">
							<xs:annotation>
								<xs:documentation>Булевый параметр. При значении false обычно не отправляется.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="choice">
							<xs:annotation>
								<xs:documentation>Группа зависимых параметров. Одновременно используется только одна такая группа.</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="list">
							<xs:annotation>
								<xs:documentation>Набор допустимых значений</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="read">
							<xs:annotation>
								<xs:documentation>Не изменяемый параметр [обычно обязательный]</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="show">
							<xs:annotation>
								<xs:documentation>Набор placeholder'ов</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="text">
							<xs:annotation>
								<xs:documentation>Простое текстовое поле</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="option">
		<xs:annotation>
			<xs:documentation>Фиксированное значение параметра</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="value" type="xs:string" use="required">
						<xs:annotation>
							<xs:documentation>Значение</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="name" type="xs:string">
						<xs:annotation>
							<xs:documentation>Идентификатор зависимого запроса</xs:documentation>
						</xs:annotation>
					</xs:attribute>
					<xs:attribute name="fill" type="xs:boolean">
						<xs:annotation>
							<xs:documentation>Признак основного запроса. При успешном выполнении запроса с идентификтором "name" заполняется данный placeholder</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="operation">
		<xs:annotation>
			<xs:documentation>Набор запросов</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="request" minOccurs="0" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Описание запроса</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="operation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Название набора запросов (из спеки)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="id" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Номер набора запросов (уникальный [по возможности из спеки])</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="list">
		<xs:annotation>
			<xs:documentation>Набор допустимых значений</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="option" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="choice">
		<xs:annotation>
			<xs:documentation>Группа зависимых параметров</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="action">
		<xs:annotation>
			<xs:documentation>Запрос</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="params">
					<xs:annotation>
						<xs:documentation>Блок параметров запроса</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="url" type="xs:anyURI" use="required">
				<xs:annotation>
					<xs:documentation>Адрес, по которому происходит запрос. Значение "psi-address" - заменяется на выбранный из выпадающего списка адрес стенда ЕРИБ.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string">
				<xs:annotation>
					<xs:documentation>Название запроса (сейчас они живут в "eribOperations.js", но надо перенести в XML)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="method" use="required">
				<xs:annotation>
					<xs:documentation>Используемый при запросе метод [post|get]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="post"/>
						<xs:enumeration value="get"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== icecube00/urib-tester/erib_Protocol.xml
<?xml version="1.0" encoding="windows-1251"?>
<!--
root:	Корневой элемент
	@specification:	Номер спецификации ЕРИБ
	operation:	Набор запросов
		@name:	Название набора запросов (из спеки)
		@id:	Номер набора запросов (уникальный [по возможности из спеки])
		request: Блок описания запроса.
			@name:	Название запроса (из спеки)
			@id:	Номер запроса (уникальный [по возможности из спеки])
			@requireUDBO:	Признак необходимости запроса УДБО (см. таблицу 3.3 в спеке)
			@service:	Ключ сервиса оказываемой услуги [используется для раграничения прав доступа] (см. таблицу 3.3 в спеке)
			action: Запрос
				@url:	Адрес, по которому происходит запрос. Значение "psi-address" - заменяется на выбранный из выпадающего списка адрес стенда ЕРИБ.
				@method:	используемый при запросе метод [post|get]
				@name:	Название запроса (сейчас они живут в "eribOperations.js", но надо перенести в XML)
				params:	Набор парамтеров запроса.
					param: Параметр запроса.
						@text:	Текстовое описание парметра
						@name:	Название параметра
						@value:	Значение по-умолчанию
						@required:	Признак обязательности параметра
						@type:	Тип параметра.
							list:	Набор допустимых значений
								option:	Фиксированное значение параметра
									@value:	Значение
									@name:	Идентификатор зависимого запроса 
									@fill:	Признак основного запроса. При успешном выполнении запроса с идентификтором "name" заполняется данный placeholder
							choice:	Группа зависимых параметров
-->
<root specification="9.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="erib_Protocol.xsd">
	<settings>
		<params>
			<param name="showAlerts" text="Debug" type="bool" required="true" value="true"/>
			<param name="alertLevel" type="text" value="0"  required="true" text="Error"/>
			<param name="showCatchedErr" type="bool" text="Выводить все ошибки" required="true" value="true"/>
		</params>
		<params>
			<param name="timeOut" text="Время ожидания ответа сервера в секундах" type="text" value="120" required="true" />
			<param name="forEmulator" type="bool" text="Формат эмулятора" required="true" value="true"/>
		</params>
		<params>
			<param type="choice">
				<choice>
					<param type="text" required="false" name="psiAddr" value="" text="Адрес сервера ЕРИБ [вручную]."/>
				</choice>
				<choice>
					<param name="psiAddr" type="list" text="Адрес сервера ЕРИБ" required="false" >
						<list>
							<option value="10.68.214.81:9080">CSA ИФТ</option>
							<option value="10.117.0.12:5577">CSA HF</option>
							<option value="10.68.5.237:9082">CSA ПСИ</option>
							<option value="10.80.238.24:8080/Emulator">Эмулятор ЕРИБ</option>
							<option value="10.67.5.219:9080">HotFix (1-й блок)</option>
							<option value="tv-erib-8r2-03:9080">HotFix (2-й блок)</option>
							<option value="10.68.5.238:9081">ПСИ (1-й блок|2-я нода)</option>
							<option value="10.68.5.238:9080">ПСИ (2-й блок|2-я нода)</option>
							<option value="10.68.214.82:9080">ИФТ (Одноблочный логон)</option>
						</list>
					</param>
				</choice>
			</param>
		</params>
		<params>
			<param name="useStatus" value="true" text="Использовать карты из ERIB-Status" type="bool" required="true" />
			<param name="mobileBank" value="true" text="МБ"  type="bool"  required="true"/>
			<param name="way4" value="true" text="Way 4"  type="bool" required="true"/>
			<param name="equalPan" value="true" text="PAN совпадает" type="bool"  required="true"/>
			<param name="chooseAgreement" value="true" text="Выбор договора" type="bool" required="true" />
			<param name="bankOffer" value="true" text="Предложения от банка" type="bool"  required="true"/>
		</params>
	</settings>
	<operation name="Аутентификация" id="4.1">
		<request name="Вход. Вариант для одноблочной архитектуры ЕРИБ." id="4.1.1" requireUDBO="false">
			<action url="http://psi-address/atm/login.do" method="post" name="logon">
				<params>
					<param text="Операция" name="operation" value="login" type="read" required="true"/>
					<param text="Номер карты пользователя, по которой произведена аутентификация" name="pan" value="" type="text" required="true"/>
					<param text="Номер устройства самообслуживания, с которого осуществляется вход." name="codeATM" value="100000" type="text" required="true"/>
					<param text="Признак карты с чипом." name="isChipCard" value="true" type="bool" required="false"/>
					<param text="ОКАТО региона (5 цифр)" name="atmRegionCode" type="list" required="false">
						<list>
							<option value="45000">г. Москва</option>
							<option value="mosobl">Московская область (корявка)</option>
							<option value="46000">Московская область г Москва</option>
							<option value="70000">Тульская обл., г.Алексин</option>
							<option value="70202">Тульская обл., г.Алексин</option>
							<option value="03000">Краснодарский край, г.Анапа</option>
							<option value="03403">Краснодарский край, Анапский район, г.Анапа</option>
							<option value="47000">Мурманская обл., г.Апатиты</option>
							<option value="47405">Мурманская обл., г.Апатиты ул.Ленина д.24</option>
							<option value="04000">Красноярский край, г.Ачинск</option>
							<option value="04403">Красноярский край, г.Ачинск ул.Дружбы Народов</option>
							<option value="10000">Амурская область, г.Благовещенск</option>
							<option value="10401">Амурская область, г.Благовещенск ул.Строителей</option>
							<option value="90000">Северная Осетия, г.Владикавказ</option>
							<option value="90401">Северная Осетия, г.Владикавказ ул.Коцоева</option>
						</list>
					</param>
				</params>
			</action>
		</request>
		<request name="Вход. Вариант для многоблочной архитектуры ЕРИБ." id="4.1.2" requireUDBO="false">
			<action url="http://psi-address/CSAATM/login.do" method="post" name="multylogon.stage1">
				<params>
					<param type="text" required="true" name="pan" value="" text="Номер карты пользователя, по которой произведена аутентификация"/>
				</params>
			</action>
		</request>
		<request name="Аутентификация по токену в указанном блоке." id="4.1.3" requireUDBO="false">
			<action url="http://psi-address/atm/postCSALogin.do" method="post" name="multylogon.stage2">
				<params>
					<param type="text" required="true" name="token" value="" text="Токен аутентификации"/>
					<param type="text" required="true" name="codeATM" value="100000" text="Номер устройства самообслуживания, с которого осуществляется вход."/>
					<param type="bool" required="false" name="isChipCard" value="true" text="Признак карты с чипом."/>
					<param type="list" required="false" name="atmRegionCode" text="ОКАТО региона (5 цифр)">
						<list>
							<option value="45000">г. Москва</option>
							<option value="mosobl">Московская область (корявка)</option>
							<option value="46000">Московская область г Москва</option>
							<option value="70000">Тульская обл., г.Алексин</option>
							<option value="70202">Тульская обл., г.Алексин</option>
							<option value="03000">Краснодарский край, г.Анапа</option>
							<option value="03403">Краснодарский край, Анапский район, г.Анапа</option>
							<option value="47000">Мурманская обл., г.Апатиты</option>
							<option value="47405">Мурманская обл., г.Апатиты ул.Ленина д.24</option>
							<option value="04000">Красноярский край, г.Ачинск</option>
							<option value="04403">Красноярский край, г.Ачинск ул.Дружбы Народов</option>
							<option value="10000">Амурская область, г.Благовещенск</option>
							<option value="10401">Амурская область, г.Благовещенск ул.Строителей</option>
							<option value="90000">Северная Осетия, г.Владикавказ</option>
							<option value="90401">Северная Осетия, г.Владикавказ ул.Коцоева</option>
						</list>
					</param>
				</params>
			</action>
		</request>
		<request name="Шаг выбора договора." id="4.1.4" requireUDBO="false">
			<action url="http://psi-address/atm/login/chooseAgreement.do" method="post" name="chooseAgreement">
				<params>
					<param type="read" required="true" name="operation" value="choose" text="Операция"/>
					<param type="text" required="true" name="agreementId" value="" text="Идентификатор выбранного договора."/>
				</params>
			</action>
		</request>
		<request name="Проверка реквизитов ДУЛ для дополнительной авторизации." id="4.1.5" requireUDBO="false">
			<action url="http://psi-address/atm/checkDUL.do" method="post" name="checkDUL">
				<params>
					<param type="text" required="true" name="code" value="" text="Последние 4 цифры документа."/>
				</params>
			</action>
		</request>
		<request name="Выход." id="4.1.6" requireUDBO="false">
			<action url="http://psi-address/atm/logoff.do" method="post" name="logoff">
				<params/>
			</action>
		</request>
	</operation>
	<operation name="Получение списка банковских продуктов" id="4.2">
		<request name="Получение списка банковских продуктов" id="4.2.0" service="Products" requireUDBO="optional">
			<action url="http://psi-address/atm/private/products/list.do" method="post" name="productsList">
				<params>
					<param type="bool" required="false" name="showProductType" value="cards" text="Карта."/>
					<param type="bool" required="false" name="showProductType" value="accounts" text="Вклад/счет."/>
					<param type="bool" required="false" name="showProductType" value="loans" text="Кредит."/>
					<param type="bool" required="false" name="showProductType" value="imaccounts" text="ОМС."/>
				</params>
			</action>
		</request>
		<request name="Получение списка банковских продуктов (вариант 2)." id="4.2.1" service="Products" requireUDBO="optional">
			<action url="http://psi-address/atm/private/products/newList.do" method="post" name="productsNewList">
				<params>
					<param type="bool" required="false" name="showProductType" value="cards" text="Карта."/>
					<param type="bool" required="false" name="showProductType" value="accounts" text="Вклад/счет."/>
					<param type="bool" required="false" name="showProductType" value="loans" text="Кредит."/>
